### ISSUE TITLE
Capacitor v6 support

### ISSUE THREAD

**Issue by clementmas** [alesmraz/capacitor-plugin-swipe-back#3]
Hi, is it possible to support Capacitor [v6](https://github.com/ionic-team/capacitor/releases/tag/6.0.0)?

```bash
npm install capacitor-swipe-back-plugin
```

I tried to install it in my application but got this error message:

```
npm ERR! code ERESOLVE could not resolve

Found: @capacitor/core@6.1.1

Could not resolve dependency:
capacitor-swipe-back-plugin@"*" from the root project

Conflicting peer dependency: @capacitor/core@5.7.7
node_modules/@capacitor/core
  peer @capacitor/core@"^5.0.0" from capacitor-swipe-back-plugin@1.0.0
```

Thanks!

**Comment by alesmraz** [comment]
Hi @clementmas 

This plugin is not ready for Capacitor v6 at the moment, but it will be soon. Please follow the releases.

Just for your info: I do not expect any breaking changes that you need to reflect in your code
